### PR TITLE
fix cards that have embedded contents

### PR DESCRIPTION
**Pull request by Floflobel**
Related to https://github.com/sqlpage/SQLPage/issues/743

### CODE REVIEW

**Comment by lovasoa** [comment]
It looks like this PR re-adds the double-border issue that was removed in v0.31 on the graphs from the example page : 


image

with this pr:

image

The problem was initially reported by @accforgithubtest in https://github.com/sqlpage/SQLPage/issues/610


It is clear that we should not disable the borders when we have `color` or `icon` set, but I'm not sure what the best behavior is when there is only a title. What do you think ?

**Comment by accforgithubtest** [comment]
> It is clear that we should not disable the borders when we have color or icon set, but I'm not sure what the best behavior is when there is only a title. What do you think ?

I might be the only one who still thinks the current behavior in v0.31 is better, when there is only a title in there. To me the double border looks worse off somehow. 
Originally I raised the issue because this would multiply the borders and empty spaces when there are 3 levels of embeded cards, etc.

**Comment by lovasoa** [comment]
> If I call my embeded with the “?_sqlpage_embed” parameter, there's a border.

We still need to separate components from one another in the embedded page. I don't think a missing border would look good when there are multiple components in the target page.

> Would be great if we can keep the behavior from the recent fix where each embedded card does add empty space and border when there is no title / text in the card, but just another embed (either iframe or sqlpage_embed).

This pull request keeps the border when there is no title.

---

```sql
select 'card' as component;
select 'xbed.sql?_sqlpage_embed' as embed;
select 'xbed.sql?_sqlpage_embed' as embed, 'red' as background_color;

select 'card' as component;
select 'xbed.sql?_sqlpage_embed' as embed, 'title' as title;
select 'xbed.sql?_sqlpage_embed' as embed, 'green' as color, 'tool' as icon;
```

now gives

image


This is not perfect, but strictly better than what we had before, I think.
This allows both your usecases: cards used strictly for layout, including deeply embedded cards (like @accforgithubtest uses), and decorated cards with just one level of embedding (like @Floflobel uses).

**Comment by lovasoa** [comment]
>     `<fieldset class="form-fieldset mb-1 p-0 {{#if _sqlpage_embed}}border-0 bg-white{{/if}}">`

@Floflobel : this looks nice in your example, but would require special handling of sqlpage_embed in all components, not just the form component...

**Comment by lovasoa** [comment]
I think we can already merge this, since it's a strict improvement over both v0.30 (where you couldn't have multiple layers of embedding) and v0.31 (where embedding with card titles or icons looked ugly).

**Pull request merged**
